name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      # TODO setup variant, service and port

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: GatewayService
          PORT_NUMBER: 8080

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 3
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"

      - name: Get Gateway logs
        if: always()  
        run: docker compose logs gateway

      - name: Get Library logs  
        if: always()
        run: docker compose logs library

      - name: Get postgres logs  
        if: always()
        run: docker compose logs postgres
        
      - name: Get all services logs
        if: always()
        run: docker compose logs

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v